### ISSUE TITLE
this template doesn't appear in your profile readme

### ISSUE THREAD

**Issue by starlightknown** [cmulay/cmulay-v1#5]
**Describe the bug**
your readme just shows hello instead of this readme
![Screenshot from 2021-05-21 21-40-08](https://user-images.githubusercontent.com/74637789/119167192-305cd280-ba7d-11eb-9b9a-1fe851cf7e8d.png)

**Screenshots**

**Additional context**
change the repo name to your username so that this will be visible in readme of your profile

**Comment by cmulay** [comment]
Thank you @starlightknown  or your interest in letting me know the issue, I'm working on v2 of my profile REAME hence changed the repo name !
