### ISSUE TITLE
Update the name of the Repo To Use As A Profile

### ISSUE THREAD

**Issue by verma-kunal** [cmulay/cmulay-v1#6]
**Is your feature request related to a problem? Please describe.**
The name of the repo is different from the username. So, this will not be displayed in your profile

**Describe the solution you'd like**
Change the repo name as your username to use this as GitHub Profile

**Comment by verma-kunal** [comment]
This issue is already raised !!

**Comment by cmulay** [comment]
Thank you @verma-kunal or your interest in letting me know the issue, I'm working on v2 of my profile REAME hence changed the repo name !
